@startuml
actor Пользователь

usecase [Просмотреть достопримечательности]
usecase [Просмотреть рестораны]
usecase [Просмотреть отели]
usecase [Применить фильтры к графикам]

Пользователь --> [Просмотреть достопримечательности]
Пользователь --> [Просмотреть рестораны]
Пользователь --> [Просмотреть отели]
Пользователь --> [Применить фильтры к графикам]
@enduml