@startuml
actor Пользователь

usecase [Выбрать тему]
usecase [Ввести число]
usecase [Получить запись из хранилища данных]

Пользователь --> [Выбрать тему]
Пользователь --> [Ввести число]
Пользователь --> [Получить запись из хранилища данных]
@enduml